"""Initial schema — TDD §6, with RLS (§18.2) and the booking exclusion constraint (§6.4).

Hand-written rather than autogenerated: the exclusion constraint and the RLS policies are
the two things this product's correctness rests on, and they should be explicit and readable.

Revision ID: 0001
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# Every tenant-scoped table. RLS is applied to all of them in one pass below; a table
# added without being listed here is caught by tests/test_tenant_isolation.py.
ORG_SCOPED_TABLES = [
    "org_domains",
    "identity_providers",
    "sites",
    "users",
    "floor_plan_assets",
    "floors",
    "zones",
    "resources",
    "groups",
    "group_members",
    "role_assignments",
    "devices",
    "refresh_tokens",
    "bookings",
    "booking_attendees",
    "checkin_events",
    "absences",
    "policies",
    "zone_permissions",
    "blackouts",
    "outbox",
    "audit_log",
]

COMMON = """
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")  # required by bookings_no_overlap
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    op.execute("""
        CREATE TYPE booking_status AS ENUM
          ('confirmed','checked_in','completed','cancelled','released_no_show')
    """)

    # ---------------------------------------------------------------- tenancy
    op.execute(f"""
        CREATE TABLE organizations (
            id uuid PRIMARY KEY,
            name text NOT NULL,
            slug text NOT NULL UNIQUE,
            primary_domain text,
            status text NOT NULL DEFAULT 'active',
            data_region text NOT NULL DEFAULT 'us',
            settings jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE org_domains (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            domain text NOT NULL UNIQUE,
            verified_at timestamptz,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE identity_providers (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            kind text NOT NULL,
            issuer text, discovery_url text, client_id text, client_secret_enc text,
            enabled boolean NOT NULL DEFAULT true,
            {COMMON}
        )
    """)

    # ------------------------------------------------------------------ space
    op.execute(f"""
        CREATE TABLE sites (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            name text NOT NULL,
            address text,
            timezone text NOT NULL,
            geo_lat double precision, geo_lng double precision,
            geofence_radius_m integer NOT NULL DEFAULT 150,
            opening_hours jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            daily_capacity_cap integer,
            checkin_enabled boolean NOT NULL DEFAULT true,
            status text NOT NULL DEFAULT 'active',
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE users (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            email citext NOT NULL,
            external_id text,
            display_name text NOT NULL,
            avatar_url text,
            locale text NOT NULL DEFAULT 'en',
            status text NOT NULL DEFAULT 'active',
            home_site_id uuid REFERENCES sites(id) ON DELETE SET NULL,
            presence_visibility text NOT NULL DEFAULT 'everyone'
                CHECK (presence_visibility IN ('everyone','team_only','nobody')),
            token_version integer NOT NULL DEFAULT 1,
            deactivated_at timestamptz,
            {COMMON},
            UNIQUE (organization_id, email)
        )
    """)
    op.execute(f"""
        CREATE TABLE floor_plan_assets (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            original_key text NOT NULL, rendered_key text,
            width_px integer NOT NULL, height_px integer NOT NULL,
            content_type text NOT NULL, checksum text,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE floors (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
            name text NOT NULL,
            ordinal integer NOT NULL DEFAULT 0,
            plan_asset_id uuid REFERENCES floor_plan_assets(id) ON DELETE SET NULL,
            plan_width_px integer, plan_height_px integer,
            published_at timestamptz,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE zones (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            floor_id uuid NOT NULL REFERENCES floors(id) ON DELETE CASCADE,
            name text NOT NULL,
            kind text NOT NULL DEFAULT 'neighborhood',
            polygon jsonb NOT NULL DEFAULT '[]'::jsonb,
            color text,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE resources (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
            floor_id uuid NOT NULL REFERENCES floors(id) ON DELETE CASCADE,
            zone_id uuid REFERENCES zones(id) ON DELETE SET NULL,
            kind text NOT NULL CHECK (kind IN ('desk','room')),
            code text NOT NULL,
            name text,
            position jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            capacity integer NOT NULL DEFAULT 1,
            attributes jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            assigned_to_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
            bookable boolean NOT NULL DEFAULT true,
            out_of_service_reason text,
            qr_key_id integer NOT NULL DEFAULT 1,
            status text NOT NULL DEFAULT 'active',
            {COMMON},
            UNIQUE (site_id, code)
        )
    """)
    op.execute("CREATE INDEX resources_floor_kind ON resources (floor_id, kind) WHERE bookable")
    op.execute("CREATE INDEX resources_attributes_gin ON resources USING gin (attributes)")

    # ------------------------------------------------------------- people/org
    op.execute(f"""
        CREATE TABLE groups (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            name text NOT NULL,
            kind text NOT NULL DEFAULT 'team',
            parent_group_id uuid REFERENCES groups(id) ON DELETE SET NULL,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE group_members (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            group_id uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
            user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role text NOT NULL DEFAULT 'member',
            {COMMON},
            UNIQUE (group_id, user_id)
        )
    """)
    op.execute(f"""
        CREATE TABLE role_assignments (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role text NOT NULL CHECK (role IN ('employee','team_lead','site_admin','org_admin')),
            scope_type text NOT NULL DEFAULT 'org' CHECK (scope_type IN ('org','site')),
            scope_id uuid,
            {COMMON}
        )
    """)
    op.execute("CREATE INDEX role_assignments_user ON role_assignments (user_id)")
    op.execute(f"""
        CREATE TABLE devices (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            platform text NOT NULL, push_token text, app_version text,
            locale text, timezone text,
            last_seen_at timestamptz, revoked_at timestamptz,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE refresh_tokens (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            family_id uuid NOT NULL,
            token_hash text NOT NULL UNIQUE,
            expires_at timestamptz NOT NULL,
            used_at timestamptz, revoked_at timestamptz,
            {COMMON}
        )
    """)
    op.execute("CREATE INDEX refresh_tokens_family ON refresh_tokens (family_id)")

    # --------------------------------------------------------------- bookings
    op.execute(f"""
        CREATE TABLE bookings (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            resource_id uuid NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
            site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
            user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            booked_by_user_id uuid NOT NULL REFERENCES users(id),
            time_range tstzrange NOT NULL,
            local_date date NOT NULL,
            status booking_status NOT NULL DEFAULT 'confirmed',
            slot text NOT NULL DEFAULT 'full_day',
            series_id uuid,
            checkin_deadline timestamptz,
            checked_in_at timestamptz,
            checked_in_method text,
            released_at timestamptz,
            cancelled_at timestamptz,
            cancel_reason text,
            idempotency_key text,
            {COMMON}
        )
    """)

    # THE correctness mechanism (TDD §6.4). Ranges are half-open, so a booking ending at
    # 12:00 and one starting at 12:00 do not conflict. The partial WHERE means cancelled
    # and released rows stop blocking without being deleted.
    op.execute("""
        ALTER TABLE bookings ADD CONSTRAINT bookings_no_overlap
          EXCLUDE USING gist (resource_id WITH =, time_range WITH &&)
          WHERE (status IN ('confirmed','checked_in'))
    """)

    op.execute("""
        CREATE INDEX bookings_resource_date ON bookings (resource_id, local_date)
          WHERE status IN ('confirmed','checked_in')
    """)
    op.execute("CREATE INDEX bookings_user_date ON bookings (user_id, local_date DESC)")
    op.execute("""
        CREATE INDEX bookings_site_date ON bookings (site_id, local_date)
          WHERE status IN ('confirmed','checked_in')
    """)
    op.execute("""
        CREATE INDEX bookings_checkin_sweep ON bookings (checkin_deadline)
          WHERE status = 'confirmed' AND checkin_deadline IS NOT NULL
    """)
    op.execute("""
        CREATE UNIQUE INDEX bookings_idem
          ON bookings (organization_id, booked_by_user_id, idempotency_key)
          WHERE idempotency_key IS NOT NULL
    """)

    op.execute(f"""
        CREATE TABLE booking_attendees (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
            user_id uuid REFERENCES users(id) ON DELETE CASCADE,
            external_email text,
            response text NOT NULL DEFAULT 'invited',
            invited_at timestamptz, responded_at timestamptz,
            {COMMON},
            CHECK (user_id IS NOT NULL OR external_email IS NOT NULL)
        )
    """)
    op.execute("""CREATE UNIQUE INDEX booking_attendees_user
                  ON booking_attendees (booking_id, user_id) WHERE user_id IS NOT NULL""")
    op.execute("""CREATE UNIQUE INDEX booking_attendees_email
                  ON booking_attendees (booking_id, external_email)
                  WHERE external_email IS NOT NULL""")

    op.execute(f"""
        CREATE TABLE checkin_events (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
            method text NOT NULL,
            occurred_at timestamptz NOT NULL,
            client_ts timestamptz,
            geofence_pass boolean,
            raw_distance_bucket text,
            device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE absences (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            local_date date NOT NULL,
            kind text NOT NULL CHECK (kind IN ('remote','leave','travel')),
            {COMMON},
            UNIQUE (user_id, local_date)
        )
    """)

    # ----------------------------------------------------------------- policy
    op.execute(f"""
        CREATE TABLE policies (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            scope_type text NOT NULL CHECK (scope_type IN ('org','site','group')),
            scope_id uuid,
            rule_type text NOT NULL,
            config jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            enabled boolean NOT NULL DEFAULT true,
            priority integer NOT NULL DEFAULT 0,
            {COMMON}
        )
    """)
    op.execute("""CREATE INDEX policies_lookup
                  ON policies (organization_id, rule_type) WHERE enabled""")
    op.execute(f"""
        CREATE TABLE zone_permissions (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            zone_id uuid NOT NULL REFERENCES zones(id) ON DELETE CASCADE,
            group_id uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
            mode text NOT NULL DEFAULT 'exclusive'
                CHECK (mode IN ('exclusive','preferred','open_after')),
            opens_at_local time,
            {COMMON}
        )
    """)
    op.execute(f"""
        CREATE TABLE blackouts (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            site_id uuid REFERENCES sites(id) ON DELETE CASCADE,
            floor_id uuid REFERENCES floors(id) ON DELETE CASCADE,
            starts_on date NOT NULL, ends_on date NOT NULL,
            reason text,
            cancels_bookings boolean NOT NULL DEFAULT false,
            {COMMON}
        )
    """)

    # -------------------------------------------------------------------- ops
    op.execute(f"""
        CREATE TABLE outbox (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            aggregate_type text NOT NULL,
            aggregate_id uuid NOT NULL,
            event_type text NOT NULL,
            payload jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            available_at timestamptz NOT NULL DEFAULT now(),
            attempts integer NOT NULL DEFAULT 0,
            locked_until timestamptz,
            processed_at timestamptz,
            last_error text,
            {COMMON}
        )
    """)
    op.execute("""
        CREATE INDEX outbox_pending ON outbox (available_at)
          WHERE processed_at IS NULL
    """)
    op.execute(f"""
        CREATE TABLE audit_log (
            id uuid PRIMARY KEY,
            organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            actor_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
            action text NOT NULL,
            target_type text NOT NULL,
            target_id uuid,
            before jsonb, after jsonb,
            ip_hash text,
            occurred_at timestamptz NOT NULL DEFAULT now(),
            {COMMON}
        )
    """)
    op.execute("CREATE INDEX audit_log_org_time ON audit_log (organization_id, occurred_at DESC)")

    # ------------------------------------------------------------------- RLS
    # FORCE applies the policy to the table owner too, so a mistake in role setup
    # cannot silently disable tenant isolation. current_setting(..., true) returns
    # NULL when unset, and `col = NULL` is false — so no tenant context means no rows,
    # which is the safe default.
    tenant_predicate = "NULLIF(current_setting('app.org_id', true), '')::uuid"

    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organizations FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON organizations "
        f"USING (id = {tenant_predicate}) "
        f"WITH CHECK (id = {tenant_predicate})"
    )

    for table in ORG_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (organization_id = {tenant_predicate}) "
            f"WITH CHECK (organization_id = {tenant_predicate})"
        )

    # org_domains is the tenant ROUTING table and must be readable before a tenant is
    # known (FR-1.3 email -> org discovery). A SELECT-only permissive policy is added on
    # top of tenant_isolation; RLS policies are OR'd. It exposes only (domain -> org id),
    # which the caller already implied by typing their own email address. Writes stay
    # tenant-scoped. This is the single deliberate exception to strict isolation.
    op.execute("CREATE POLICY domain_routing ON org_domains FOR SELECT USING (true)")

    # Runtime role grants. Guarded so the migration also runs on a single-role database
    # (CI, a developer's local Postgres) where deskflow_app does not exist.
    op.execute("""
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'deskflow_app') THEN
            EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE
                     ON ALL TABLES IN SCHEMA public TO deskflow_app';
            EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO deskflow_app';
          END IF;
        END $$;
    """)


def downgrade() -> None:
    for t in reversed(["organizations"] + ORG_SCOPED_TABLES):
        op.execute(f"DROP TABLE IF EXISTS {t} CASCADE")
    op.execute("DROP TYPE IF EXISTS booking_status")
